### ISSUE TITLE
pinned version of nbconvert has problems with HTML blocks in markdown

### ISSUE THREAD

**Issue by itcarroll** [CryoInTheCloud/hub-image#116]
The `nbconvert` package is pinned to version 6.5.3:
https://github.com/CryoInTheCloud/hub-image/blob/03a26b80ca50c5791b730015c777dbe0bfc6b938/environment.yml#L48

As a result, the `mistune` package version is ... quite outdated.

As a result, certain markdown content (particularly HTML blocks) does not get converted to HTML correctly.

Can `nbconvert` be unpinned? I don't see a reason it is pinned, and in NASA-Openscapes hub it is not present at all (comes in from `jupyter-server`, I think.). I've just tried a `conda update -n notebook -c conda-forge --all` and it happily upgrades `nbconvert` to "7.16.4". And the upgrade solves my markdown rendering problem.

**Comment by weiji14** [comment]
Hi @itcarroll, I've opened up a PR at https://github.com/CryoInTheCloud/hub-image/pull/117 to upgrade `nbconvert` to 7.16.4. See if that looks ok and we can merge that in.
