### ISSUE TITLE
Commit conda-lock.yml to repository

### ISSUE THREAD

**Issue by scottyhq** [CryoInTheCloud/hub-image#122]
It would be useful to commit the unified lockfile to this repository in addition to the platform-specific 
https://github.com/CryoInTheCloud/hub-image/blob/main/conda-linux-64.lock

This would facilitate installing the cryocloud environment (at least the conda-forge part) on different systems
https://github.com/ICESAT-2HackWeek/website-2024/pull/17#discussion_r1706100624

**Comment by weiji14** [comment]
Maybe time for me to pick up on https://github.com/CryoInTheCloud/hub-image/pull/14 again :laughing: Do we want both the `conda-lock.yml` file and `conda-linux-64.lock` file?

**Comment by weiji14** [comment]
Oh wait actually, #14 might have been chewing on too much as it was trying to install from the `conda-lock.yml` via a `postBuild` script. I can open a separate smaller PR for just adding a `conda-lock.yml` file.

**Comment by scottyhq** [comment]
Yeah for starters just linux-64 `conda-lock.yml` in addition to `conda-linux-64.lock` would be useful.

```
conda-lock lock -p linux-64
conda-lock render -k explicit -p linux-64
```

Looks like other platforms aren't happy with a few of the packages:
```
Could not lock the environment for platform osx-64
Could not solve for environment specs
The following package could not be installed
└─ ocl-icd-system does not exist (perhaps a typo or a missing channel).
```
