### ISSUE TITLE
update conda-lock version after updates

### ISSUE THREAD

**Issue by JessicaS11** [CryoInTheCloud/hub-image#15]
The most recent ([v1.1.3](https://github.com/conda-incubator/conda-lock/releases/tag/v1.1.3)) version of conda-lock includes a switch (that happened in v1.1.0 with [PR#89](https://github.com/conda-incubator/conda-lock/pull/189)) from relative to absolute paths. As a result, whenever someone new updates the conda lock files, their local dir path is added to the lockfile source list (and other users get a warning for every path listed that's not on their local machine). It looks like [a fix is in the works](https://github.com/conda-incubator/conda-lock/issues/229), so I reverted to v1.0.5 until this update is implemented. @weiji14, please let me know if this will be an issue for anything you added and we can deal with the warnings until the update lets us specify relative paths.

**Comment by JessicaS11** [comment]
Conda-lock has officially closed this issue as fixed (not sure if it's yet released): https://github.com/conda/conda-lock/issues/229

**Comment by weiji14** [comment]
[Conda-lock 2.0.0](https://github.com/conda/conda-lock/releases/tag/v2.0.0) was released which also included https://github.com/conda/conda-lock/pull/328 that handles the relative paths a bit better still. I'll update the GitHub Actions workflow to use conda-lock 2.0.0 in #14.

**Comment by weiji14** [comment]
This issue is actually referring to the lockfile on https://github.com/CryoInTheCloud/CryoCloudWebsite/tree/main/conda (where the build stuff used to happen). We've been using `conda-lock>=2.0.0` for a while now on https://github.com/CryoInTheCloud/hub-image (`conda-lock=2.3.0` as of #91), so I'll close down this issue. Feel free to reopen if needed.
