### ISSUE TITLE
How to access the hub?

### ISSUE THREAD

**Issue by scottyhq** [CryoInTheCloud/hub-image#34]
@weiji14 @tsnow03 i just tried to log into https://hub.cryointhecloud.com but am denied despite being an organization member, is access still limited to specific teams?

**Comment by weiji14** [comment]
Hmm, seems like you weren't added to the `CryoCloudUser` team. I just added you in, can you try again?

**Comment by scottyhq** [comment]
yep, that was it! thanks @weiji14
