### ISSUE TITLE
Use GDAL >=3.6 for k8s JupyterHub Image

### ISSUE THREAD

**Issue by scottyhq** [CryoInTheCloud/hub-image#35]
GDAL has built-in cloud credential session handling that previously did not work well with K8s. Basically opening s3://bucket/raster.tif would end up with 'Unable to open' or other credential-related errors, see https://github.com/OSGeo/gdal/issues/4058 for details.

If you use GDAL>=3.6 (rasterio>=1.3.4) accessing data stored in S3 via rasterio and GDAL should be smoother.

cc @tsnow03 @fperez @weiji14

**Comment by weiji14** [comment]
> If you use GDAL>=3.6 (rasterio>=1.3.4) accessing data stored in S3 via rasterio and GDAL should be smoother.

I will say that GDAL=3.6 packages have been a broken mess on conda-forge recently, see e.g. https://github.com/conda-forge/qgis-feedstock/issues/276 and https://github.com/conda-forge/fiona-feedstock/pull/202. Best to wait until the dust settles a bit :slightly_smiling_face:
