### ISSUE TITLE
Add public storage folder where all users have read/write permissions

### ISSUE THREAD

**Issue by tsnow03** [CryoInTheCloud/hub-image#43]
We need to create a public storage folder because workshop groups are going to be working in CryoCloud soon and all users will need to freely share data across the entire group. 

@MattF-NSIDC @trey-stafford and QGreenland (May 22-25) will definitely need this feature for a relatively small group. @elliesch and @facusapienza21 may also need this for the Norwegian ML workshop held on April 16-21, but it may be necessary for them to have a completely separate file sharing folder that is only linked to their GitHub Team so that data storage can be more easily monitored. 

We need input from @colliand @jmunroe and the 2i2c team to understand if there are ways to make storage folders only visible and writable by certain GitHub teams and if this is the use model we want to adopt for some of the more resource intensive events we support.

**Comment by jmunroe** [comment]
Is the need for block file storage (conventional, filenames and paths) or object storage (e.g. Zarr datasets) ?  The shared/ folder already exists for the purpose of sharing files between groups (although that's readable to everyone and writable by hub-admins)

I'll get feedback from the 2i2c engineering team on options when it comes to assigning permissions and access controls to storage resources.

**Comment by tsnow03** [comment]
Conventional. They need something that all users can read/write to and we would like to keep our shared-readwrite separate from that. I think some hubs have used a public folder for this in the past, but I'm not sure if this is still the best solution. Thank you @jmunroe!

**Comment by tsnow03** [comment]
@jmunroe would you mind assigning this task and the (small server task)[https://github.com/orgs/CryoInTheCloud/projects/1/views/2#:~:text=Add%20a%20couple%20smaller%20server%20options%20to%20initial%20menu%3F] to someone? I'm not sure who would work on this. Is this something you would like me to email the 2i2c help to request?

**Comment by jmunroe** [comment]
This exactly the kind of request best made via support@2i2c.org so it gets action by one of the 2i2c cloud engineers.

**Comment by tsnow03** [comment]
We settled on wanting to add a public storage folder that everyone has read/write permissions for. 

We would also like to know if it is possible to have a storage folder related to an event that only a specific GitHub team can read and write from - allowing us to more easily monitor the data storage use for an event.

**Comment by jmunroe** [comment]
Having a storage folder that is accessible by on specific GitHub teams is not something that exists yet. But it is a feature that 2i2c is investigating. There is preliminary work that would first need to be done on user managed JupyterHub groups:
 - https://github.com/2i2c-org/infrastructure/issues/2306

I don't have timeline on when such a feature could be rolled-out but feedback from communites like CryoCloud will help us prioritize where to focus our development efforts.

**Comment by tsnow03** [comment]
The shared-public folder looks great! Is there anything else still being worked on for this issue? If not, we can close it!
