### ISSUE TITLE
Requester pays fix needed

### ISSUE THREAD

**Issue by tsnow03** [CryoInTheCloud/hub-image#52]
I believe we are having requester pays authentication errors again that we need to fix. I'm unable to open Landsat imagery and it appears to be requester pays authorization issues like we had back in October, but i'm not positive. I'm wondering if something got lost when we transitioned to the shared servers. I just noticed it. I've left code in the CryoCloud shared > Landsat_cloud_example.ipynb to replicate the errors. Any ideas on what we need to do to fix it? An example of the error is here:

<img width="679" alt="Screenshot 2023-04-03 at 5 42 23 PM" src="https://user-images.githubusercontent.com/12904976/230990813-fdfcef11-88f7-4336-b12d-b4069c551ca0.png">

**Comment by pnasrat** [comment]
AWS Session code here https://github.com/rasterio/rasterio/blob/main/rasterio/session.py#L242

**Comment by pnasrat** [comment]
Ok looking at the buckets configured in the cluster the scratch buckets don't have it enabled

https://docs.aws.amazon.com/AmazonS3/latest/userguide/RequesterPaysExamples.html

However terraform config here implies does https://github.com/2i2c-org/infrastructure/blob/master/terraform/aws/projects/nasa-cryo.tfvars#L53

**Comment by pnasrat** [comment]
Ok my initial understanding was a bit confused (still learning) continuing investigation but think I've a better understanding. I'll respond on the support tickect.
