### ISSUE TITLE
Shared-readwrite folder not writeable by members of CryoCloudAdvanced team

### ISSUE THREAD

**Issue by fperez** [CryoInTheCloud/hub-image#6]
I thought that write access to the `~/shared-readwrite` folder was controlled by mebership in the "Advanced Users" github team, but I'm not able to write to the folder despite being in the group.

Am I mistaken in how those permissions are being managed?

**Comment by yuvipanda** [comment]
These are writeable by folks marked as 'admin' in the jupyterhub, not via any GitHub team. We currently don't have a way to mark folks as admins via group membership. The current best practice way to add admins is to make a PR to this list: https://github.com/2i2c-org/infrastructure/blob/master/config/clusters/nasa-cryo/common.values.yaml#L46

**Comment by fperez** [comment]
Ah, understood, thanks @yuvipanda! I see the parameters for #7 are also in that same file.

Quick question: do you think it would make sense for that file to live in the hub-image repo, so everything is in one place? Or does that complicate things on the 2i2c end?

If the latter, I understand - in that case we can just document which topics (like node selection or admin rights) need to be dealt with there, and how. I'm looking for the pattern that is easiest, on balance, for both the community users and the 2i2c team.

**Comment by yuvipanda** [comment]
@fperez I think we'll have the hub-image separate from the hub config, as it also separates who can have merge rights easily. We can try figure out longer term how folks can also self-merge a subset of config changes easily, but I think this split is sort of how it'll be in the future. I hope datahub moves here too.

**Comment by fperez** [comment]
Thx @yuvipanda - we'll just add a note in the docs on where that info lives.

**Comment by fperez** [comment]
Fixed [here](https://github.com/2i2c-org/infrastructure/pull/1958). Thx @sgibson91!
