### ISSUE TITLE
Add ITS_LIVE python library 

### ISSUE THREAD

**Issue by betolink** [CryoInTheCloud/hub-image#71]
ITS_LIVE just released a new Python library to get point time series of all land ice, an example notebook can be viewed here 
https://nbviewer.org/github/nasa-jpl/itslive-py/blob/main/notebooks/introduction.ipynb

The library is available via pip or conda

`- itslive>=0.2.0`

**Comment by weiji14** [comment]
Could you push an itslive==0.2.0 to conda-forge by merging https://github.com/conda-forge/itslive-feedstock/pull/2? It looks like only 0.1.7 is available at https://anaconda.org/conda-forge/itslive/files currently. I can start a PR to add it after, or you can add it to the environment.yml file following https://github.com/CryoInTheCloud/hub-image#updating-packages-in-this-repository
