### ISSUE TITLE
requesting aws cli and H5Coro

### ISSUE THREAD

**Issue by betolink** [CryoInTheCloud/hub-image#79]
We are at the IS2 Hackweek working with HDF5 data and it will be nice if the base image had

* awscli v2 (either the official binary or the community maintained https://anaconda.org/conda-forge/awscliv2)
* [H5Coro](https://anaconda.org/conda-forge/h5coro)

**Comment by weiji14** [comment]
Ok, let me add those in, I really wanted to use aws-cli too just now!
