### ISSUE TITLE
Package updates - August 2023

### ISSUE THREAD

**Issue by weiji14** [CryoInTheCloud/hub-image#86]
Tracking a list of packages to add/update as requested from CryoCloud Slack:

High priority:
- [x] ESM https://github.com/CryoInTheCloud/hub-image/pull/87
  - [x]  :arrow_up: Intake-ESM 2022.9.18 to 2023.x.x
  - [x] :heavy_plus_sign: XMIP
  - [x] :heavy_plus_sign: ESMPy/ESMF (http://earthsystemmodeling.org/esmpy/)
- [x] :arrow_up: Bokeh v2 to v3 https://github.com/CryoInTheCloud/hub-image/pull/94
- [x] :heavy_plus_sign: PyGMT https://github.com/CryoInTheCloud/hub-image/pull/89

Low priority:
- [ ] :arrow_up: QGIS 3.28 Firenze to QGIS 3.32 Lima
- [ ] :arrow_up: JupyterLab v3 to v4 (once all the jupyter extensions are compatible with v4)
- [ ] :heavy_plus_sign: https://github.com/silx-kit/jupyterlab-h5web

P.S. Feel free anyone to open a Pull Request to add the above updates.

**Comment by jkingslake** [comment]
can we add [gcsfs](https://gcsfs.readthedocs.io/en/latest/) too, please? Thanks!

**Comment by jkingslake** [comment]
After talking to @tsnow03 today at the WAIS meeting, I went ahead and made a PR for this: https://github.com/CryoInTheCloud/hub-image/pull/92

**Comment by tsnow03** [comment]
Great work guys! I'll get to this in a few days but I'll be updating to the new ipython and new sliderule soon also.

**Comment by weiji14** [comment]
Scott has updated Sliderule to v4 already at #93. Bokeh v3 is also almost ready at #94. We can do IPython right after that.

**Comment by tsnow03** [comment]
Great! I want to check in on JupyterLab 4.0. Do you have a good mental model for this and can I help work on this? @weiji14 @scottyhq

**Comment by weiji14** [comment]
These are the JupyterLab extensions in the `environment.yml` file. Those compatible with JupyterLab 4.0 are ticked:

- [x] jupyter-resource-usage https://github.com/jupyter-server/jupyter-resource-usage/pull/195
- [ ] jupyterlab-favorites ? https://github.com/NERSC/jupyterlab-favorites
- [x] jupyterlab-geojson https://github.com/jupyterlab/jupyter-renderers/pull/300
- [ ] jupyterlab-git==0.41.0 https://github.com/jupyterlab/jupyterlab-git/pull/1236
- [x] jupyterlab-myst==1.1.0 https://github.com/executablebooks/jupyterlab-myst/pull/155

From the list above, it seems like `jupyterlab-git` is close to ready. Not sure if we should drop `jupyterlab-favorites`, it doesn't look particularly maintained (last commit in Nov 2021.

Oh, and there might be a few other packages that needs to be bumped as well (e.g. those with interactive widgets), so we'll need to try things carefully using the Binder link and/or the staging server first.

**Comment by weiji14** [comment]
It's a new year :partying_face:, so I'm gonna close this issue in favour of #102. Will try to work on the JupyterLab 4 update this week.
