### ISSUE TITLE
Documentation for hub configurator not working to change docker image

### ISSUE THREAD

**Issue by scottyhq** [CryoInTheCloud/hub-image#96]
I was following these docs:
https://github.com/CryoInTheCloud/hub-image#updating-the-cryocloud-jupyterhub-to-use-a-new-image

But no matter what the configurator is set to (I tried the latest http://quay.io/cryointhecloud/cryo-hub-image:b25e78527b0c) hub will pull the image set here:

https://github.com/2i2c-org/infrastructure/blob/0f265f493b8280f6432cc275a431229774c848e6/config/clusters/nasa-cryo/common.values.yaml#L140 

possibly related to using the profile list for different node types (https://github.com/2i2c-org/infrastructure/issues/3135#issuecomment-1764328026)

**Comment by yuvipanda** [comment]
@scottyhq yes, unfortunately when the image is overriden per-profile, it doesn't pull from the configurator anymore. https://github.com/yuvipanda/z2jh-configurator is the eventual answer to this, but it's not been deployed anywhere right now.

**Comment by tsnow03** [comment]
We need to update the readme (https://github.com/CryoInTheCloud/hub-image?tab=readme-ov-file#updating-the-cryocloud-jupyterhub-to-use-a-new-image) to use the Other option to test the new image.

**Comment by tsnow03** [comment]
This has been added. Let me know if you have any further issues or updates.
